# For more information on how to use this template please refer to:
# http://tardis-sn.github.io/tardis/development/continuous_integration.html

name: documentation-build

on:
  push:

jobs:
  documentation_preview:
    runs-on: ubuntu-latest

    if: github.repository_owner != 'tardis-sn' && (contains(github.ref, 'doc') || contains(github.event.head_commit.message, '[build_docs]'))

    steps:
      - uses: actions/checkout@v2

      - name: Setup TARDIS Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
            environment-file: tardis_env3.yml
            activate-environment: tardis
            channels: conda-forge
            mamba-version: "*"

      - name: Install TARDIS
        shell: bash -l {0}
        run: python setup.py install

      - name: Build Sphinx Documentation
        shell: bash -l {0}
        run: python setup.py build_docs

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html/
          publish_branch: gh-pages
          destination_dir: ${{ steps.extract_branch.outputs.branch }}
